### ISSUE TITLE
Estamos atentos, si encontramos algo te avisamos!

### ISSUE THREAD

**Issue by esteblock** [josemoragonzalez/Defunciones#1]
Hola, que buena iniciativa, en https://github.com/YachayData/COVID-19 estábamos buscando estos datos.
Asi que estaremos pendiente de tu repositorio. Si encontramos algo del 2020 te avisamos!

**Comment by josemoragonzalez** [comment]
@estebaniglesias Súper, ya pedí los datos por transparencia hace dos semanas, estoy a la espera de que llegue algo, en cuanto llegue lo subo, se agradece si encuentran algo y lo pueden compartir!

**Comment by pescap** [comment]
Hola José, trabajo con @estebaniglesias!

Propongo scrapear: https://obituario.cl/
Cada página tiene URL: 
https://obituario.cl/?page=x
Al 4 de mayo, estamos con x=[1, ..., 865]
La última página corresponde al día 16/04/2019
Cada página tiene 10 personas.

No sé de dónde sacan estos datos.
La idea sería hacer un for[1,...,865] en todas las páginas y obtener la fecha para cada persona, para sacar la serie de tiempo del número de personas por día.

Hice unas pruebas a mano y parece que no hay un aumento grande de los casos últimamente, les envío el script.

¿Qué opinas?

**Comment by josemoragonzalez** [comment]
Hola @pescap !! me parece un excelente aporte, lamentablemente no hay data lo suficientemente antigua como para haber realizado un contraste con la cifra oficial, pero cuando lleguen los datos que solicité por transparencia (si es que llegan), podemos contrastar y saber si podemos usarlo como fuente.

**Comment by josemoragonzalez** [comment]
Estimados @pescap y @estebaniglesias ya hay datos de certificados de defunción en https://estadisticas.sed.srcei.cl/
